spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/project?servertimezone=UTC
    url: jdbc:mysql://mysql205.c0inhtd4aeqi.ap-northeast-2.rds.amazonaws.com/project?serverTimezone=UTC
    username: bit
    password: bit
       
mybatis:
  mapper-locations: com/bitcamp/app/member/mapper/**/*.xml
     
server:
  port: 8080